CREATE OR REPLACE TABLE TEST.SH.COUNTRIES (
COUNTRY_ID NUMBER ,
COUNTRY_ISO_CODE VARCHAR ,
COUNTRY_NAME VARCHAR ,
COUNTRY_SUBREGION VARCHAR ,
COUNTRY_SUBREGION_ID NUMBER ,
COUNTRY_REGION VARCHAR ,
COUNTRY_REGION_ID NUMBER ,
COUNTRY_TOTAL VARCHAR ,
COUNTRY_TOTAL_ID NUMBER ,
COUNTRY_NAME_HIST VARCHAR NOT NULL)