CREATE OR REPLACE TABLE TEST.SH.PROMOTIONS (
PROMO_ID NUMBER(6) ,
PROMO_NAME VARCHAR ,
PROMO_SUBCATEGORY VARCHAR ,
PROMO_SUBCATEGORY_ID NUMBER ,
PROMO_CATEGORY VARCHAR ,
PROMO_CATEGORY_ID NUMBER ,
PROMO_COST NUMBER(10,2) ,
PROMO_BEGIN_DATE None ,
PROMO_END_DATE None ,
PROMO_TOTAL VARCHAR ,
PROMO_TOTAL_ID NUMBER )